ACTIVE_STATES = {
    "CREATED",
    "SUBMITTING",
    "ACKNOWLEDGED",
    "PARTIAL",
    "RECONCILING",
    "CANCEL_PENDING",
}

BLOCKED_MUTATION_STATES = {
    "UNCERTAIN",
    "FILLED",
    "REJECTED",
    "CANCELLED",
    "EXPIRED",
    "DEADLETTER",
}

TERMINAL_STATES = {
    "FILLED",
    "REJECTED",
    "CANCELLED",
    "EXPIRED",
    "DEADLETTER",
}