from config.env_loader import Env

class Settings:

    CAPITAL = Env.CAPITAL

    MAX_RISK_PER_TRADE = 0.01

    MAX_DRAWDOWN = 0.15

    MAX_TRADES_PER_DAY = 50

    PAPER_MODE = not Env.LIVE_TRADING

    BROKER_LOCK_AFTER_LOSSES = 3
    BROKER_REOPEN_MINUTES = 30
    POST_COOLDOWN_RISK_MULTIPLIER = 0.5

    CORRELATION_CAP = 2

    OVERTRADING_WARNING_THRESHOLD = 8
    OVERTRADING_WINDOW_MINUTES = 30